
spring:
  mvc:
    async:
      request-timeout: 600000
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      connection-test-query: "SELECT 1"
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 90000
      connection-timeout: 30000
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      jdbc:
        batch_size: 50
      order_inserts: true
      order_updated: true

redirect:
  url: https://127.0.0.1:5000/
  
server:
  port: 8081

springdoc:
  swagger-ui:
    path: /trade/swagger-ui.html
  api-docs:
    path: /trade/v3/api-docs
